box = "centos/7"
forwarded_ports = [[8080, 8081], [22, 2221]]        # 0: guest, 1: host
inline_script = ["echo 'Hello World'", "whoami"]
script = "sample.sh"
box_check_update = true                     # default
allow_fstab_modification = true             # default
allow_hosts_modification = true             # default
boot_timeout = 300                          # default
box_download_insecure = false               # default
graceful_halt_timeout = 60                  # default
hostname = "vagranter"
ignores_box_vagrantfile = false             # default
public_network = "192.168.42.10"
private_network = "192.168.43.10"
post_up_message = "VM is now ready to use!"
synced_folder = [["./", "/var/www"]]        # multiple synced folders can be defined; 0: host, 1: guest
usable_port_range = [2200, 2250]            # default
ansible_playbook = "playbook.yml"
